const BLUE_BOX = 32;
const RED_BOX = 33;
const GREEN_BOX = 34;
const BROWN_BOX = 35;
const YELLOW_BOX = 36;
const PURPLE_BOX = 37;

const BLUE_BOX_MARKED = 48;
const RED_BOX_MARKED = 49;
const GREEN_BOX_MARKED = 50;
const BROWN_BOX_MARKED = 51;
const YELLOW_BOX_MARKED = 52;
const PURPLE_BOX_MARKED = 53;

const NORMAL_BOX = 38;

export {
  BLUE_BOX,
  RED_BOX,
  GREEN_BOX,
  BROWN_BOX,
  YELLOW_BOX,
  PURPLE_BOX,

  NORMAL_BOX,

  BLUE_BOX_MARKED,
  RED_BOX_MARKED,
  GREEN_BOX_MARKED,
  BROWN_BOX_MARKED,
  YELLOW_BOX_MARKED,
  PURPLE_BOX_MARKED
}