const BLUE_TARGET = 40;
const RED_TARGET = 41;
const GREEN_TARGET = 42;
const BROWN_TARGET = 43;
const YELLOW_TARGET = 44;
const PURPLE_TARGET = 45;

export {
  BLUE_TARGET,
  RED_TARGET,
  GREEN_TARGET,
  BROWN_TARGET,
  YELLOW_TARGET,
  PURPLE_TARGET
}